[tools]
crush = "latest"

[env]
OPENROUTER_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEFNS2pZdyBXdm5qdmw0VXZpRXN2eXZMQ25pYS8ycDI2bzFBNEwxbnJzU09XbmtJVkI4CkVGT1orL011N2F3MDM2c2JKelBWRnh6b2VKTVoxTXp2QXk5SWl3SXNUM1UKLT4gJ2ktZ3JlYXNlIEgoMjZ6SiA4dm9vVnYmKSArO3YKcDM1ZS9qVTNweW1OYktobDZKaVh3WVQwek12d3lDN1lIWStDQkZSYUc1aVkwN2F5bnJRT2dOdWxkS2ExSVhuVApDdTJkYWplNzJ2ZFF1QXdtczBoU1o2RDJlalRkSlV3Ylo5M1F6UjU1ekdaaVpPZThXMHBsT2dlUGJYVQotLS0gZ3dMdksyV2F2THZWMGd1UEROR3NyYjlURFBRdit5dzRJVVE3ZGNFYkVkawowuOhtigluuSqxMv8gQMvS1aBBep+SQZC7WC03pxLZzlFEMbtn0f9tDVkbJUg1LuL1wRrc/BfRou3KwsKd+lWri2kwGPWCu+5B9jAG5HsYLX0BV/K9A720bT7zzjcn9MSk42AWa3kCK5U" }
