services:
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: MySpeed
    env_file:
      - ../common.env
    ports:
      - ${LAN_IP}:5216:5216
      - ${TAILSCALE_IP}:5216:5216
    volumes:
      - myspeed:/myspeed/data
    restart: always

volumes:
  myspeed: