services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    env_file:
      - ../common.env
    restart: always
    ports:
      - ${LAN_IP}:5001:5001
      - ${TAILSCALE_IP}:5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockge-data:/app/data
      - /home/dietpi/server.local:/home/dietpi/server.local
    environment:
      - DOCKGE_STACKS_DIR=/home/dietpi/server.local

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    env_file:
      - ../common.env
    ports:
      - ${LAN_IP}:8084:8080
      - ${TAILSCALE_IP}:8084:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle-data:/data
    restart: unless-stopped