services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=media_net
      - --providers.file.directory=/etc/traefik/dynamic
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.forwardedheaders.trustedips=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - --experimental.plugins.bouncer.version=v1.4.4
      - --log.level=INFO
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik/dynamic:ro
      - ./certs:/certs:ro
      - ./traefik/logs:/var/log/traefik
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecMode=stream

      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiScheme=http
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiHost=crowdsec:8080
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiKey=${CROWDSEC_LAPI_KEY}
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecEnabled=true
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecHost=crowdsec:7422
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecFailureBlock=true
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecUnreachableBlock=true
    networks:
      - media_net
    restart: always

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./ddclient:/config
    restart: always

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      - BOUNCER_KEY_TRAEFIK=${CROWDSEC_LAPI_KEY}
      - TZ=${TZ}
    volumes:
      - ./crowdsec/acquis.d:/etc/crowdsec/acquis.d:ro
      - crowdsec_data:/var/lib/crowdsec/data
      - ./traefik/logs:/var/log/traefik:ro
    networks:
      - media_net
    restart: always

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${LAN_IP}:8080:8080 # qBittorrent Web UI (LAN)
      - ${TAILSCALE_IP}:8080:8080 # qBittorrent Web UI (Tailscale)
      - ${LAN_IP}:9696:9696 # Prowlarr Web UI (LAN)
      - ${TAILSCALE_IP}:9696:9696 # Prowlarr Web UI (Tailscale)

    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
      - WIREGUARD_MTU=1280
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
    networks:
      - media_net
    healthcheck:
      test: ping -c 1 1.1.1.1 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    restart: always

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS}
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_DIR}:/data
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:8989:8989
      - ${TAILSCALE_IP}:8989:8989

    networks:
      - media_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8989/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:7878:7878
      - ${TAILSCALE_IP}:7878:7878

    networks:
      - media_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:6767:6767
      - ${TAILSCALE_IP}:6767:6767

    networks:
      - media_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6767 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./jellyseerr:/app/config
    ports:
      - ${LAN_IP}:5055:5055
      - ${TAILSCALE_IP}:5055:5055

    networks:
      - media_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.mrbhanuka.dev`)
      - traefik.http.routers.jellyseerr.entrypoints=websecure
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.routers.jellyseerr.middlewares=crowdsec@docker

      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:5055/api/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./jellyfin:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:8096:8096
      - ${TAILSCALE_IP}:8096:8096

    networks:
      - media_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.mrbhanuka.dev`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.middlewares=crowdsec@docker

      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  media_net:
    name: media_net
    driver: bridge

volumes:
  crowdsec_data:
