services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    env_file:
      - ../common.env
    profiles:
      - download
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${LAN_IP}:8080:8080 # qBittorrent Web UI (LAN)
      - ${TAILSCALE_IP}:8080:8080 # qBittorrent Web UI (Tailscale)
      - ${LAN_IP}:9696:9696 # Prowlarr Web UI (LAN)
      - ${TAILSCALE_IP}:9696:9696 # Prowlarr Web UI (Tailscale)

    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
    networks:
      - media_net
    healthcheck:
      test: ping -c 1 1.1.1.1 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    restart: always

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    env_file:
      - ../common.env
    profiles:
      - download
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_DIR}:/data
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    container_name: prowlarr
    env_file:
      - ../common.env
    profiles:
      - download
    volumes:
      - ./prowlarr:/config
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    env_file:
      - ../common.env
    volumes:
      - ./radarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:7878:7878
      - ${TAILSCALE_IP}:7878:7878

    networks:
      - media_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    env_file:
      - ../common.env
    profiles:
      - download
    volumes:
      - ./bazarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:6767:6767
      - ${TAILSCALE_IP}:6767:6767

    networks:
      - media_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6767 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - ../common.env
    volumes:
      - ./jellyseerr:/app/config
    ports:
      - ${LAN_IP}:5055:5055
      - ${TAILSCALE_IP}:5055:5055

    networks:
      - media_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.mrbhanuka.dev`)
      - traefik.http.routers.jellyseerr.entrypoints=websecure
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.routers.jellyseerr.middlewares=crowdsec@docker
      - traefik.http.routers.jellyseerr.loadbalancer.server.port=5055
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:5055/api/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    env_file:
      - ../common.env
    volumes:
      - ./jellyfin:/config
      - ${MEDIA_DIR}:/data
    ports:
      - ${LAN_IP}:8096:8096
      - ${TAILSCALE_IP}:8096:8096

    networks:
      - media_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.mrbhanuka.dev`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.middlewares=crowdsec@docker
      - traefik.http.routers.jellyfin.loadbalancer.server.port=8096
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  media_net:
    external: true