services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    env_file:
      - .env
    ports:
      - ${LAN_IP}:3001:3001
      - ${TAILSCALE_IP}:3001:3001
    volumes:
      - ./data:/app/data
    restart: always
