daemon=300
syslog=yes
ssl=yes

# Detect public IPv4
use=web, web=api.ipify.org

protocol=cloudflare
zone=mrbhanuka.dev
login=token
password_env=CLOUDFLARE_API_TOKEN

# Update both proxied DNS records
jellyfin.mrbhanuka.dev,jellyseerr.mrbhanuka.dev
